export const popularIcons = [
  { name: 'file-text', label: 'File Text' }, { name: 'file-pdf', label: 'File Pdf' }, { name: 'person-square', label: 'Person Square' },
  { name: 'clipboard-pulse', label: 'Clipboard Pulse' }, { name: 'filetype-html', label: 'Filetype Html' }, { name: 'menu-app-fill', label: 'Menu App Fill' }, { name: 'globe2', label: 'Globe2' },
  { name: 'house', label: 'House' }, { name: 'house-fill', label: 'House Fill' }, { name: 'person', label: 'Person' },
  { name: 'person-fill', label: 'Person Fill' }, { name: 'gear', label: 'Gear' }, { name: 'gear-fill', label: 'Gear Fill' },
  { name: 'search', label: 'Search' }, { name: 'plus', label: 'Plus' }, { name: 'dash', label: 'Dash' },
  { name: 'x', label: 'X' }, { name: 'check', label: 'Check' }, { name: 'check-all', label: 'Check All' },
  { name: 'info-circle', label: 'Info Circle' }, { name: 'info-circle-fill', label: 'Info Circle Fill' },
  { name: 'exclamation-circle', label: 'Exclamation Circle' }, { name: 'exclamation-circle-fill', label: 'Exclamation Circle Fill' },
  { name: 'question-circle', label: 'Question Circle' }, { name: 'question-circle-fill', label: 'Question Circle Fill' },
  { name: 'trash', label: 'Trash' }, { name: 'trash-fill', label: 'Trash Fill' }, { name: 'pencil', label: 'Pencil' },
  { name: 'pencil-fill', label: 'Pencil Fill' }, { name: 'pencil-square', label: 'Pencil Square' }, { name: 'save', label: 'Save' },
  { name: 'save-fill', label: 'Save Fill' }, { name: 'download', label: 'Download' }, { name: 'upload', label: 'Upload' },
  { name: 'share', label: 'Share' }, { name: 'share-fill', label: 'Share Fill' }, { name: 'link', label: 'Link' },
  { name: 'link-45deg', label: 'Link 45deg' }, { name: 'eye', label: 'Eye' }, { name: 'eye-fill', label: 'Eye Fill' },
  { name: 'eye-slash', label: 'Eye Slash' }, { name: 'eye-slash-fill', label: 'Eye Slash Fill' }, { name: 'bell', label: 'Bell' },
  { name: 'bell-fill', label: 'Bell Fill' }, { name: 'heart', label: 'Heart' }, { name: 'heart-fill', label: 'Heart Fill' },
  { name: 'star', label: 'Star' }, { name: 'star-fill', label: 'Star Fill' }, { name: 'bookmark', label: 'Bookmark' },
  { name: 'bookmark-fill', label: 'Bookmark Fill' }, { name: 'flag', label: 'Flag' }, { name: 'flag-fill', label: 'Flag Fill' },
  { name: 'funnel', label: 'Funnel' }, { name: 'funnel-fill', label: 'Funnel Fill' }, { name: 'filter', label: 'Filter' },
  { name: 'sort-down', label: 'Sort Down' }, { name: 'sort-up', label: 'Sort Up' }, { name: 'three-dots', label: 'Three Dots' },
  { name: 'three-dots-vertical', label: 'Three Dots Vertical' }, { name: 'arrow-left', label: 'Arrow Left' },
  { name: 'arrow-right', label: 'Arrow Right' }, { name: 'arrow-up', label: 'Arrow Up' }, { name: 'arrow-down', label: 'Arrow Down' },
  { name: 'arrow-left-short', label: 'Arrow Left Short' }, { name: 'arrow-right-short', label: 'Arrow Right Short' },
  { name: 'arrow-up-short', label: 'Arrow Up Short' }, { name: 'arrow-down-short', label: 'Arrow Down Short' },
  { name: 'chevron-left', label: 'Chevron Left' }, { name: 'chevron-right', label: 'Chevron Right' },
  { name: 'chevron-up', label: 'Chevron Up' }, { name: 'chevron-down', label: 'Chevron Down' },
  { name: 'chevron-double-left', label: 'Chevron Double Left' }, { name: 'chevron-double-right', label: 'Chevron Double Right' },
  { name: 'chevron-double-up', label: 'Chevron Double Up' }, { name: 'chevron-double-down', label: 'Chevron Double Down' },
  { name: 'arrow-repeat', label: 'Arrow Repeat' }, { name: 'arrow-clockwise', label: 'Arrow Clockwise' },
  { name: 'arrow-counterclockwise', label: 'Arrow Counterclockwise' }, { name: 'arrow-left-right', label: 'Arrow Left Right' },
  { name: 'arrow-up-down', label: 'Arrow Up Down' }, { name: 'arrow-return-left', label: 'Arrow Return Left' },
  { name: 'arrow-return-right', label: 'Arrow Return Right' }, { name: 'caret-left', label: 'Caret Left' },
  { name: 'caret-right', label: 'Caret Right' }, { name: 'caret-up', label: 'Caret Up' }, { name: 'caret-down', label: 'Caret Down' },
  { name: 'caret-left-fill', label: 'Caret Left Fill' }, { name: 'caret-right-fill', label: 'Caret Right Fill' },
  { name: 'caret-up-fill', label: 'Caret Up Fill' }, { name: 'caret-down-fill', label: 'Caret Down Fill' },
  { name: 'list', label: 'List' }, { name: 'grid', label: 'Grid' }, { name: 'grid-3x3-gap', label: 'Grid 3x3 Gap' },
  { name: 'menu-button', label: 'Menu Button' }, { name: 'menu-button-wide', label: 'Menu Button Wide' },
  { name: 'menu-up', label: 'Menu Up' }, { name: 'menu-down', label: 'Menu Down' }, { name: 'chat', label: 'Chat' },
  { name: 'chat-fill', label: 'Chat Fill' }, { name: 'chat-dots', label: 'Chat Dots' }, { name: 'chat-dots-fill', label: 'Chat Dots Fill' },
  { name: 'chat-left', label: 'Chat Left' }, { name: 'chat-right', label: 'Chat Right' }, { name: 'envelope', label: 'Envelope' },
  { name: 'envelope-fill', label: 'Envelope Fill' }, { name: 'envelope-open', label: 'Envelope Open' },
  { name: 'envelope-open-fill', label: 'Envelope Open Fill' }, { name: 'telephone', label: 'Telephone' },
  { name: 'telephone-fill', label: 'Telephone Fill' }, { name: 'send', label: 'Send' }, { name: 'send-fill', label: 'Send Fill' },
  { name: 'at', label: 'At' }, { name: 'broadcast', label: 'Broadcast' }, { name: 'rss', label: 'Rss' },
  { name: 'facebook', label: 'Facebook' }, { name: 'twitter', label: 'Twitter' }, { name: 'instagram', label: 'Instagram' },
  { name: 'linkedin', label: 'Linkedin' }, { name: 'github', label: 'Github' }, { name: 'google', label: 'Google' },
  { name: 'whatsapp', label: 'Whatsapp' }, { name: 'youtube', label: 'Youtube' }, { name: 'discord', label: 'Discord' },
  { name: 'slack', label: 'Slack' }, { name: 'telegram', label: 'Telegram' }, { name: 'twitch', label: 'Twitch' },
  { name: 'reddit', label: 'Reddit' }, { name: 'tiktok', label: 'Tiktok' }, { name: 'file-earmark', label: 'File Earmark' },
  { name: 'file-earmark-fill', label: 'File Earmark Fill' }, { name: 'file-earmark-text', label: 'File Earmark Text' },
  { name: 'file-earmark-pdf', label: 'File Earmark Pdf' }, { name: 'file-earmark-image', label: 'File Earmark Image' },
  { name: 'file-earmark-code', label: 'File Earmark Code' }, { name: 'file-earmark-zip', label: 'File Earmark Zip' },
  { name: 'folder', label: 'Folder' }, { name: 'folder-fill', label: 'Folder Fill' }, { name: 'folder2', label: 'Folder2' },
  { name: 'folder-plus', label: 'Folder Plus' }, { name: 'folder-minus', label: 'Folder Minus' },
  { name: 'folder-check', label: 'Folder Check' }, { name: 'archive', label: 'Archive' }, { name: 'archive-fill', label: 'Archive Fill' },
  { name: 'clipboard', label: 'Clipboard' }, { name: 'clipboard-check', label: 'Clipboard Check' },
  { name: 'clipboard-data', label: 'Clipboard Data' }, { name: 'clipboard-plus', label: 'Clipboard Plus' },
  { name: 'journal', label: 'Journal' }, { name: 'journal-text', label: 'Journal Text' }, { name: 'book', label: 'Book' },
  { name: 'book-fill', label: 'Book Fill' }, { name: 'camera', label: 'Camera' }, { name: 'camera-fill', label: 'Camera Fill' },
  { name: 'camera-video', label: 'Camera Video' }, { name: 'camera-video-fill', label: 'Camera Video Fill' },
  { name: 'image', label: 'Image' }, { name: 'image-fill', label: 'Image Fill' }, { name: 'images', label: 'Images' },
  { name: 'play', label: 'Play' }, { name: 'play-fill', label: 'Play Fill' }, { name: 'pause', label: 'Pause' },
  { name: 'pause-fill', label: 'Pause Fill' }, { name: 'stop', label: 'Stop' }, { name: 'stop-fill', label: 'Stop Fill' },
  { name: 'skip-start', label: 'Skip Start' }, { name: 'skip-end', label: 'Skip End' }, { name: 'volume-up', label: 'Volume Up' },
  { name: 'volume-down', label: 'Volume Down' }, { name: 'volume-mute', label: 'Volume Mute' }, { name: 'mic', label: 'Mic' },
  { name: 'mic-fill', label: 'Mic Fill' }, { name: 'headphones', label: 'Headphones' }, { name: 'music-note', label: 'Music Note' },
  { name: 'laptop', label: 'Laptop' }, { name: 'phone', label: 'Phone' }, { name: 'tablet', label: 'Tablet' },
  { name: 'display', label: 'Display' }, { name: 'pc-display', label: 'Pc Display' }, { name: 'watch', label: 'Watch' },
  { name: 'smartwatch', label: 'Smartwatch' }, { name: 'keyboard', label: 'Keyboard' }, { name: 'mouse', label: 'Mouse' },
  { name: 'printer', label: 'Printer' }, { name: 'tv', label: 'Tv' }, { name: 'cart', label: 'Cart' },
  { name: 'cart-fill', label: 'Cart Fill' }, { name: 'cart-plus', label: 'Cart Plus' }, { name: 'cart-check', label: 'Cart Check' },
  { name: 'bag', label: 'Bag' }, { name: 'bag-fill', label: 'Bag Fill' }, { name: 'bag-plus', label: 'Bag Plus' },
  { name: 'bag-check', label: 'Bag Check' }, { name: 'credit-card', label: 'Credit Card' },
  { name: 'credit-card-2-front', label: 'Credit Card 2 Front' }, { name: 'wallet', label: 'Wallet' },
  { name: 'wallet2', label: 'Wallet2' }, { name: 'cash', label: 'Cash' }, { name: 'cash-stack', label: 'Cash Stack' },
  { name: 'coin', label: 'Coin' }, { name: 'currency-dollar', label: 'Currency Dollar' },
  { name: 'currency-euro', label: 'Currency Euro' }, { name: 'currency-bitcoin', label: 'Currency Bitcoin' },
  { name: 'tag', label: 'Tag' }, { name: 'tag-fill', label: 'Tag Fill' }, { name: 'shop', label: 'Shop' },
  { name: 'shop-window', label: 'Shop Window' }, { name: 'calendar', label: 'Calendar' },
  { name: 'calendar-fill', label: 'Calendar Fill' }, { name: 'calendar-event', label: 'Calendar Event' },
  { name: 'calendar-check', label: 'Calendar Check' }, { name: 'clock', label: 'Clock' }, { name: 'clock-fill', label: 'Clock Fill' },
  { name: 'clock-history', label: 'Clock History' }, { name: 'stopwatch', label: 'Stopwatch' }, { name: 'alarm', label: 'Alarm' },
  { name: 'alarm-fill', label: 'Alarm Fill' }, { name: 'sun', label: 'Sun' }, { name: 'sun-fill', label: 'Sun Fill' },
  { name: 'moon', label: 'Moon' }, { name: 'moon-fill', label: 'Moon Fill' }, { name: 'cloud', label: 'Cloud' },
  { name: 'cloud-fill', label: 'Cloud Fill' }, { name: 'cloud-rain', label: 'Cloud Rain' }, { name: 'cloud-snow', label: 'Cloud Snow' },
  { name: 'cloud-lightning', label: 'Cloud Lightning' }, { name: 'thermometer-half', label: 'Thermometer Half' },
  { name: 'wind', label: 'Wind' }, { name: 'key', label: 'Key' }, { name: 'key-fill', label: 'Key Fill' },
  { name: 'lock', label: 'Lock' }, { name: 'lock-fill', label: 'Lock Fill' }, { name: 'unlock', label: 'Unlock' },
  { name: 'unlock-fill', label: 'Unlock Fill' }, { name: 'shield', label: 'Shield' }, { name: 'shield-fill', label: 'Shield Fill' },
  { name: 'shield-check', label: 'Shield Check' }, { name: 'shield-lock', label: 'Shield Lock' },
  { name: 'trophy', label: 'Trophy' }, { name: 'trophy-fill', label: 'Trophy Fill' }, { name: 'award', label: 'Award' },
  { name: 'award-fill', label: 'Award Fill' }, { name: 'gift', label: 'Gift' }, { name: 'gift-fill', label: 'Gift Fill' },
  { name: 'briefcase', label: 'Briefcase' }, { name: 'briefcase-fill', label: 'Briefcase Fill' }, { name: 'tools', label: 'Tools' },
  { name: 'wrench', label: 'Wrench' }, { name: 'hammer', label: 'Hammer' }, { name: 'screwdriver', label: 'Screwdriver' },
  { name: 'nut', label: 'Nut' }, { name: 'gear-wide', label: 'Gear Wide' }, { name: 'lightbulb', label: 'Lightbulb' },
  { name: 'lightbulb-fill', label: 'Lightbulb Fill' }, { name: 'battery-full', label: 'Battery Full' },
  { name: 'battery-half', label: 'Battery Half' }, { name: 'battery-low', label: 'Battery Low' },
  { name: 'lightning', label: 'Lightning' }, { name: 'lightning-fill', label: 'Lightning Fill' },
  { name: 'people', label: 'People' }, { name: 'people-fill', label: 'People Fill' },
  { name: 'person-plus', label: 'Person Plus' }, { name: 'person-minus', label: 'Person Minus' },
  { name: 'person-check', label: 'Person Check' }, { name: 'person-circle', label: 'Person Circle' },
  { name: 'person-badge', label: 'Person Badge' }, { name: 'person-vcard', label: 'Person Vcard' },
  { name: 'gender-male', label: 'Gender Male' }, { name: 'gender-female', label: 'Gender Female' },
  { name: 'heart-pulse', label: 'Heart Pulse' }, { name: 'hospital', label: 'Hospital' }, { name: 'capsule', label: 'Capsule' },
  { name: 'thermometer', label: 'Thermometer' }, { name: 'activity', label: 'Activity' },
  { name: 'geo-alt', label: 'Geo Alt' }, { name: 'geo-alt-fill', label: 'Geo Alt Fill' }, { name: 'pin-map', label: 'Pin Map' },
  { name: 'pin-map-fill', label: 'Pin Map Fill' }, { name: 'map', label: 'Map' }, { name: 'map-fill', label: 'Map Fill' },
  { name: 'compass', label: 'Compass' }, { name: 'compass-fill', label: 'Compass Fill' }, { name: 'airplane', label: 'Airplane' },
  { name: 'airplane-fill', label: 'Airplane Fill' }, { name: 'train-front', label: 'Train Front' },
  { name: 'car-front', label: 'Car Front' }, { name: 'bicycle', label: 'Bicycle' }, { name: 'truck', label: 'Truck' },
  { name: 'fuel-pump', label: 'Fuel Pump' }, { name: 'building', label: 'Building' }, { name: 'house-door', label: 'House Door' },
  { name: 'house-door-fill', label: 'House Door Fill' }, { name: 'circle', label: 'Circle' },
  { name: 'circle-fill', label: 'Circle Fill' }, { name: 'square', label: 'Square' }, { name: 'square-fill', label: 'Square Fill' },
  { name: 'triangle', label: 'Triangle' }, { name: 'triangle-fill', label: 'Triangle Fill' }, { name: 'diamond', label: 'Diamond' },
  { name: 'diamond-fill', label: 'Diamond Fill' }, { name: 'pentagon', label: 'Pentagon' }, { name: 'hexagon', label: 'Hexagon' },
  { name: 'octagon', label: 'Octagon' }, { name: 'patch-check', label: 'Patch Check' },
  { name: 'patch-check-fill', label: 'Patch Check Fill' }, { name: 'patch-exclamation', label: 'Patch Exclamation' },
  { name: 'patch-question', label: 'Patch Question' }, { name: 'layers', label: 'Layers' },
  { name: 'layers-fill', label: 'Layers Fill' }, { name: 'stack', label: 'Stack' }, { name: 'box', label: 'Box' },
  { name: 'box-seam', label: 'Box Seam' }, { name: 'cup-hot', label: 'Cup Hot' }, { name: 'puzzle', label: 'Puzzle' }
];
